env:
  secure: "cvr23mTiKuVsCj/89oEt4oKtrHglcW37kQ7QdAVDzybm1iQqEwqLcJanFU93Xs1YooUlGfhOQFlNcnlShWpQFhe7Qu3xew+U1T+V4WlKo11zqlxxgb+7BNcnUU4N9BrhnB8ife1dGOgEDrnzb9wqEetWOp5LW3NmoWI3chCixayTp5oMdGMV/F/WCFGoHbvbS8u8EvN9Co06phtQeWKaPwdWXDxTfZwRBBDfjijNK1lR2FH+mYjGyTsmLto+71nypIDI6Db/cUCD6mHZy3yMQDL/6vpiBCOUl/GIqNsMy2Lr1KMrvYM5g4QGR6KfFFuMD6rfmj7VXE5JjMtwlOXFPEjIrt5rMQ4cs13NRKssxIk0ciymEfAt0+FI6VYkFRH5lIrl5eSWlkKrVQnCcwDoevBeAEdeSzIMk18Y+jhY25XtJyHZV7b8rSyozOiKWr3V51hZ6pLCgmrCkmROTyrgaZPPNymVH4EFrsCqu6GLOmE4I1t8wkwM2afqxLkCMBvlr0vd32C+rlzX48i635VDMwy+HsezChySPEgtO3XEmGMrx7SuwuUz52sx15dPZDCDaT++Owo407SvZfrDRgs8pC/fd6pWk9H3YoF5DWGn8/MDp9QaZBkuw1wwpElWYG8ZMD8PWxT4CVSuEgvmlvvOMUQxxhHcbY2wAPtUbLaHKRc="
language: python
python:
- '3.5'
- '3.6'
addons:
  apt:
    packages:
    - xvfb
    - imagemagick
    - ghostscript
install:
- pip install -r requirements.txt
- pip install pyinstaller wheel bumpversion
script:
- xvfb-run pytest
- pyinstaller bin/invoicex_linux.spec
after_success:
- git config --global user.email "bumpversion-after-ci@example.com"
- git config --global user.name "Bumpversion after CI"
- bumpversion --verbose patch
- git push --tags
deploy:
  provider: pypi
  user: duskybomb
  password:
    secure: y2Hs0+XgzRC3dLaJ6yEQMhaYmJIy4A0QhR4KiyUVe5nZ8NZyZiLxOU4+06sebOvilPMKQGvXd+ohjxLKldXrZ4aRFH1haDDcQ5P8BJHE7Efouhn+xdwsKbkRqYoA/59f92OEN7Ua9+q14zGsBgvc+UKhxlj2E3zDFM7nHxpebhZnHP6xVsPKV1JV//JpQou3GpclnSaeJShpW/+nH86gHt1CUqLa6bb5VChj7pGlHrVUH7ritDRGbIVHCtKbR96XygZg+Qk0HsNwJGZrz7SeKTWAQICBirQr2ZSHprKPC2P9ez4RgIjfRwD+4LENyxIh5/pMpG/BkN12raIH3Yhdd6XuYXF0wweIztXJY4HxRfWYGA5vXyZPyBHy9gDlMpH24RR98j2XVoK9+ltkw49X0EiD7BmxfD4Y9/Kin6TBy2iNUpj8Z2IhGiJY0rLpSSP32AVn9CchF2mSE55nkXEH20Xxs++URHdAQHfijhADP59Ly2nI0sU6ISel4hC3O7TH6z/cBCRXcn4jo5FafDsZsK0lAqLhp478w/Ytm4w/G1sY20pzeMrgoGZKY3M+0cBYqfTKFVfJfm4+oHOHx7v2ZpwdrXyNfVrULLZTNdn4SmgIvQbQ/Mfkbpnz3SmIDOsW3poIzNaBoDY73jaPecfIMML5C8XdBmvhHtCXrNcXBj0=
  on:
    distributions: sdist bdist_wheel
    repo: invoice-x/invoicex-gui
    tags: true