language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - xvfb
    - imagemagick
    - ghostscript
install:
- pip install -r requirements.txt
- pip install pyinstaller wheel bumpversion
script:
- xvfb-run pytest
- pyinstaller bin/invoicex_linux.spec
after_success:
- git config --global user.email "bumpversion-after-ci@example.com"
- git config --global user.name "Bumpversion after CI"
- git clone https://${GH_TOKEN}@github.com/invoice-x/invoicex-gui.git
- cd invoicex-gui
- bumpversion --verbose patch
- git push origin master --tags
deploy:
  provider: pypi
  user: duskybomb
  password:
    secure: y2Hs0+XgzRC3dLaJ6yEQMhaYmJIy4A0QhR4KiyUVe5nZ8NZyZiLxOU4+06sebOvilPMKQGvXd+ohjxLKldXrZ4aRFH1haDDcQ5P8BJHE7Efouhn+xdwsKbkRqYoA/59f92OEN7Ua9+q14zGsBgvc+UKhxlj2E3zDFM7nHxpebhZnHP6xVsPKV1JV//JpQou3GpclnSaeJShpW/+nH86gHt1CUqLa6bb5VChj7pGlHrVUH7ritDRGbIVHCtKbR96XygZg+Qk0HsNwJGZrz7SeKTWAQICBirQr2ZSHprKPC2P9ez4RgIjfRwD+4LENyxIh5/pMpG/BkN12raIH3Yhdd6XuYXF0wweIztXJY4HxRfWYGA5vXyZPyBHy9gDlMpH24RR98j2XVoK9+ltkw49X0EiD7BmxfD4Y9/Kin6TBy2iNUpj8Z2IhGiJY0rLpSSP32AVn9CchF2mSE55nkXEH20Xxs++URHdAQHfijhADP59Ly2nI0sU6ISel4hC3O7TH6z/cBCRXcn4jo5FafDsZsK0lAqLhp478w/Ytm4w/G1sY20pzeMrgoGZKY3M+0cBYqfTKFVfJfm4+oHOHx7v2ZpwdrXyNfVrULLZTNdn4SmgIvQbQ/Mfkbpnz3SmIDOsW3poIzNaBoDY73jaPecfIMML5C8XdBmvhHtCXrNcXBj0=
  distributions: "sdist bdist_wheel"
  on:
    repo: invoice-x/invoicex-gui
    tags: false
env:
  global:
    secure: U2zwsYCwUjXgyFo54izCamB6JVx8beu6VXHOdnoTv3YaaQu4rhMArpXvyni0XNbQ8MkZhMPVB1Ls7A26A37YposXvUNM9NkIUwyaokS8PPRd52NljRMLUJQFp6upC1GbK1n4hzSICKg31A7LztmEqSA0cnRHDp/WkRRUBhLrsp02oBFiSWY6la1X6f1OzGA7S9i1GZpiwnqKQkeW8YG2FzYQ8gQlNncSKrzI27WuTjJdMkywNN7c9lNxEyrK9hB2verDyckkrAzyZwEVp+u00GAtfj8vU3Om+xUSCEysC9gvon3A+xxemX/53qKhK45iiHNa4/zqYRQld8P6jlRgOGViey1EP2v/H372BmeQBU0qT4cEk2icy07ucBKQQ6OMlxc5A+GJIGQnDtCUlB3aZ4PdNAnMThSSPJvvS5TXGVpEpkWA0VcFeIoMbZdfuFLA/XExFSzkoe68O4u5YxL/HIPJlIjKA3j2+oid6Co0Boz/9cKGaqQMoE9zbXHSvoD+FzKSfdZsc8TeWK+HPeIqG7j/BYa5LwJm9IYje8WowAxAja4/QTXHMgUBrU6L/eRXtl2SDfc8LfaSwfJcgvowUNjYf6zeHL1MnXBlxZzLZTFbt5R5RD6Zwh+PhrHdTxze8LohE/bGBmwGvFBgiBfoaZao+lxEyUnkeHAlRIilHjE=
notifications:
  email: false